# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockup', '0003_auto_20171105_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_customer',
            field=models.BooleanField(default=True),
        ),
    ]
