# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockup', '0004_profile_is_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ethereum_address',
            field=models.CharField(default='', max_length=50),
        ),
    ]
